In [18]:
print("reck98")
!(which python)
!(python --version)

reck98
/run/media/reck98/Others/Development/ML_NLP_DL/dl/.venv/bin/python
Python 3.12.12

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split


import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers



import warnings
warnings.filterwarnings("ignore")

In [20]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [21]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [22]:
X = df.drop("needs_water", axis=1)
y = df["needs_water"]

In [23]:
X

    soil_moisture  temperature_c  sunlight_hours
0            0.10             34               9
1            0.15             30               8
2            0.20             26               7
3            0.25             22               4
4            0.40             28               8
5            0.60             30              10
6            0.35             19               3
7            0.18             22              10
8            0.45             35              12
9            0.05             24               5
10           0.80             33               9
11           0.27             33              11
12           0.55             21               2
13           0.70             25               6
14           0.12             20               1
15           0.30             29               9

In [24]:
X_min = X.min()
X_max = X.max()
X = (X - X_min) / (X_max - X_min + 1e-8)

In [25]:
X

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [27]:
X_train

    soil_moisture  temperature_c  sunlight_hours
13       0.866667         0.3750        0.454545
11       0.293333         0.8750        0.909091
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
2        0.200000         0.4375        0.545455
15       0.333333         0.6250        0.727273
4        0.466667         0.5625        0.636364
7        0.173333         0.1875        0.818182
10       1.000000         0.8750        0.727273
12       0.666667         0.1250        0.090909
3        0.266667         0.1875        0.272727
6        0.400000         0.0000        0.181818

In [28]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'), 
    layers.Dense(1, activation='sigmoid')
])

In [29]:
model.compile(
    optimizer='sgd', 
    loss='binary_crossentropy', 
    metrics=['accuracy']
)

In [31]:

history = model.fit(
    X_train.values,
    y_train.values,
    epochs=1000,
    validation_data=(X_test.values, y_test.values),
    batch_size=4,
    verbose=1
)

Epoch 1/1000
1/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.6476

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.6333 - val_accuracy: 0.2500 - val_loss: 0.7513
Epoch 2/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5833 - loss: 0.6338 - val_accuracy: 0.2500 - val_loss: 0.7510
Epoch 3/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.6327 - val_accuracy: 0.2500 - val_loss: 0.7508
Epoch 4/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.6325 - val_accuracy: 0.2500 - val_loss: 0.7505
Epoch 5/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6324 - val_accuracy: 0.2500 - val_loss: 0.7502
Epoch 6/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5833 - loss: 0.6319 - val_accuracy: 0.2500 - val_loss: 0.7500
Epoch 7/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5833 - loss: 0.6315 - val_accuracy: 0.2500 - val_loss: 0.7497
Epoch 8/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6318 - val_accuracy: 0.2500 - val_loss: 0.7494
Epoch 9/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6310 - val_accuracy: 0.2500 - val_loss: 0.7491
Epoch 10/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6306 - val_accuracy: 0.2500 - val_loss: 0.7489
Epoch 11/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6303 - val_accuracy: 0.2500 - val_loss: 0.7486
Epoch 12/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6309 - val_accuracy: 0.2500 - val_loss: 0.7483
Epoch 13/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5833 - loss: 0.6303 - val_accuracy: 0.2500 - val_loss: 0.7480
Epoch 14/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6305 - val_accuracy: 0.2500 - val_loss: 0.7478
Epoch 15/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5833 - loss: 0.6296 - val_accuracy: 0.2500 - val_loss: 0.7475
Epoch 16/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.6289 - val_accuracy: 0.2500 - val_loss: 0.7472
Epoch 17/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5833 - loss: 0.6291 - val_accuracy: 0.2500 - val_loss: 0.7469
Epoch 18/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5833 - loss: 0.6287 - val_accuracy: 0.2500 - val_loss: 0.7466
Epoch 19/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6281 - val_accuracy: 0.2500 - val_loss: 0.7463
Epoch 20/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6276 - val_accuracy: 0.2500 - val_loss: 0.7460
Epoch 21/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6273 - val_accuracy: 0.2500 - val_loss: 0.7457
Epoch 22/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6277 - val_accuracy: 0.2500 - val_loss: 0.7455
Epoch 23/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6267 - val_accuracy: 0.2500 - val_loss: 0.7452
Epoch 24/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6265 - val_accuracy: 0.2500 - val_loss: 0.7449
Epoch 25/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6262 - val_accuracy: 0.2500 - val_loss: 0.7446
Epoch 26/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6263 - val_accuracy: 0.2500 - val_loss: 0.7442
Epoch 27/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6261 - val_accuracy: 0.2500 - val_loss: 0.7440
Epoch 28/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6258 - val_accuracy: 0.2500 - val_loss: 0.7437
Epoch 29/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6250 - val_accuracy: 0.2500 - val_loss: 0.7434
Epoch 30/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6250 - val_accuracy: 0.2500 - val_loss: 0.7430
Epoch 31/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6242 - val_accuracy: 0.2500 - val_loss: 0.7427
Epoch 32/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6239 - val_accuracy: 0.2500 - val_loss: 0.7424
Epoch 33/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6247 - val_accuracy: 0.2500 - val_loss: 0.7420
Epoch 34/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6237 - val_accuracy: 0.2500 - val_loss: 0.7418
Epoch 35/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6229 - val_accuracy: 0.2500 - val_loss: 0.7414
Epoch 36/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6233 - val_accuracy: 0.2500 - val_loss: 0.7411
Epoch 37/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6223 - val_accuracy: 0.2500 - val_loss: 0.7408
Epoch 38/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6228 - val_accuracy: 0.2500 - val_loss: 0.7405
Epoch 39/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6223 - val_accuracy: 0.2500 - val_loss: 0.7401
Epoch 40/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6224 - val_accuracy: 0.2500 - val_loss: 0.7398
Epoch 41/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6215 - val_accuracy: 0.2500 - val_loss: 0.7394
Epoch 42/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6206 - val_accuracy: 0.2500 - val_loss: 0.7391
Epoch 43/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6205 - val_accuracy: 0.2500 - val_loss: 0.7388
Epoch 44/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6199 - val_accuracy: 0.2500 - val_loss: 0.7384
Epoch 45/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6201 - val_accuracy: 0.2500 - val_loss: 0.7381
Epoch 46/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6201 - val_accuracy: 0.2500 - val_loss: 0.7378
Epoch 47/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6189 - val_accuracy: 0.2500 - val_loss: 0.7374
Epoch 48/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6187 - val_accuracy: 0.2500 - val_loss: 0.7371
Epoch 49/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6184 - val_accuracy: 0.2500 - val_loss: 0.7367
Epoch 50/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6185 - val_accuracy: 0.2500 - val_loss: 0.7364
Epoch 51/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6187 - val_accuracy: 0.2500 - val_loss: 0.7361
Epoch 52/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6173 - val_accuracy: 0.2500 - val_loss: 0.7357
Epoch 53/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6182 - val_accuracy: 0.2500 - val_loss: 0.7353
Epoch 54/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6167 - val_accuracy: 0.2500 - val_loss: 0.7350
Epoch 55/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6161 - val_accuracy: 0.2500 - val_loss: 0.7346
Epoch 56/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6163 - val_accuracy: 0.2500 - val_loss: 0.7342
Epoch 57/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6156 - val_accuracy: 0.2500 - val_loss: 0.7339
Epoch 58/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6151 - val_accuracy: 0.2500 - val_loss: 0.7335
Epoch 59/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6160 - val_accuracy: 0.2500 - val_loss: 0.7332
Epoch 60/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6143 - val_accuracy: 0.2500 - val_loss: 0.7328
Epoch 61/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6141 - val_accuracy: 0.2500 - val_loss: 0.7324
Epoch 62/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6138 - val_accuracy: 0.2500 - val_loss: 0.7320
Epoch 63/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6142 - val_accuracy: 0.2500 - val_loss: 0.7317
Epoch 64/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6130 - val_accuracy: 0.2500 - val_loss: 0.7313
Epoch 65/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6133 - val_accuracy: 0.2500 - val_loss: 0.7310
Epoch 66/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6122 - val_accuracy: 0.2500 - val_loss: 0.7306
Epoch 67/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6121 - val_accuracy: 0.2500 - val_loss: 0.7302
Epoch 68/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6123 - val_accuracy: 0.2500 - val_loss: 0.7298
Epoch 69/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6112 - val_accuracy: 0.2500 - val_loss: 0.7295
Epoch 70/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6119 - val_accuracy: 0.2500 - val_loss: 0.7291
Epoch 71/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6107 - val_accuracy: 0.2500 - val_loss: 0.7287
Epoch 72/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6100 - val_accuracy: 0.2500 - val_loss: 0.7284
Epoch 73/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6103 - val_accuracy: 0.2500 - val_loss: 0.7280
Epoch 74/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6094 - val_accuracy: 0.2500 - val_loss: 0.7276
Epoch 75/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6094 - val_accuracy: 0.2500 - val_loss: 0.7272
Epoch 76/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6085 - val_accuracy: 0.2500 - val_loss: 0.7268
Epoch 77/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6082 - val_accuracy: 0.2500 - val_loss: 0.7264
Epoch 78/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6079 - val_accuracy: 0.2500 - val_loss: 0.7260
Epoch 79/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6082 - val_accuracy: 0.2500 - val_loss: 0.7256
Epoch 80/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6071 - val_accuracy: 0.2500 - val_loss: 0.7253
Epoch 81/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6066 - val_accuracy: 0.2500 - val_loss: 0.7249
Epoch 82/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6070 - val_accuracy: 0.2500 - val_loss: 0.7245
Epoch 83/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6062 - val_accuracy: 0.2500 - val_loss: 0.7241
Epoch 84/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6055 - val_accuracy: 0.2500 - val_loss: 0.7237
Epoch 85/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6056 - val_accuracy: 0.2500 - val_loss: 0.7233
Epoch 86/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6047 - val_accuracy: 0.2500 - val_loss: 0.7228
Epoch 87/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6043 - val_accuracy: 0.2500 - val_loss: 0.7224
Epoch 88/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6041 - val_accuracy: 0.2500 - val_loss: 0.7220
Epoch 89/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6036 - val_accuracy: 0.2500 - val_loss: 0.7216
Epoch 90/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6031 - val_accuracy: 0.2500 - val_loss: 0.7212
Epoch 91/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6031 - val_accuracy: 0.2500 - val_loss: 0.7208
Epoch 92/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6030 - val_accuracy: 0.2500 - val_loss: 0.7203
Epoch 93/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6026 - val_accuracy: 0.2500 - val_loss: 0.7200

Epoch 94/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6020 - val_accuracy: 0.2500 - val_loss: 0.7195
Epoch 95/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6011 - val_accuracy: 0.2500 - val_loss: 0.7191
Epoch 96/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6013 - val_accuracy: 0.2500 - val_loss: 0.7187
Epoch 97/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6007 - val_accuracy: 0.2500 - val_loss: 0.7183
Epoch 98/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5998 - val_accuracy: 0.2500 - val_loss: 0.7179
Epoch 99/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.5997 - val_accuracy: 0.2500 - val_loss: 0.7175
Epoch 100/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5991 - val_accuracy: 0.2500 - val_loss: 0.7171
Epoch 101/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.5997 - val_accuracy: 0.2500 - val_loss: 0.7166
Epoch 102/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.5987 - val_accuracy: 0.2500 - val_loss: 0.7161
Epoch 103/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5982 - val_accuracy: 0.2500 - val_loss: 0.7157
Epoch 104/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5974 - val_accuracy: 0.2500 - val_loss: 0.7152
Epoch 105/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5970 - val_accuracy: 0.2500 - val_loss: 0.7148
Epoch 106/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5971 - val_accuracy: 0.2500 - val_loss: 0.7143
Epoch 107/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5983 - val_accuracy: 0.2500 - val_loss: 0.7139
Epoch 108/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5960 - val_accuracy: 0.2500 - val_loss: 0.7134
Epoch 109/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.5955 - val_accuracy: 0.2500 - val_loss: 0.7130
Epoch 110/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.5949 - val_accuracy: 0.2500 - val_loss: 0.7125
Epoch 111/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5944 - val_accuracy: 0.2500 - val_loss: 0.7121
Epoch 112/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.5943 - val_accuracy: 0.2500 - val_loss: 0.7116
Epoch 113/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5940 - val_accuracy: 0.2500 - val_loss: 0.7112
Epoch 114/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5933 - val_accuracy: 0.2500 - val_loss: 0.7107
Epoch 115/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5929 - val_accuracy: 0.2500 - val_loss: 0.7102
Epoch 116/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5931 - val_accuracy: 0.2500 - val_loss: 0.7098
Epoch 117/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5919 - val_accuracy: 0.2500 - val_loss: 0.7093
Epoch 118/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5913 - val_accuracy: 0.2500 - val_loss: 0.7089
Epoch 119/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5909 - val_accuracy: 0.2500 - val_loss: 0.7084
Epoch 120/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5928 - val_accuracy: 0.2500 - val_loss: 0.7079
Epoch 121/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5901 - val_accuracy: 0.2500 - val_loss: 0.7075
Epoch 122/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5910 - val_accuracy: 0.2500 - val_loss: 0.7070
Epoch 123/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5892 - val_accuracy: 0.2500 - val_loss: 0.7066
Epoch 124/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5888 - val_accuracy: 0.2500 - val_loss: 0.7061
Epoch 125/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5883 - val_accuracy: 0.2500 - val_loss: 0.7056
Epoch 126/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5879 - val_accuracy: 0.2500 - val_loss: 0.7052
Epoch 127/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5895 - val_accuracy: 0.2500 - val_loss: 0.7048
Epoch 128/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5870 - val_accuracy: 0.2500 - val_loss: 0.7043
Epoch 129/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.5865 - val_accuracy: 0.2500 - val_loss: 0.7038
Epoch 130/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5863 - val_accuracy: 0.2500 - val_loss: 0.7034
Epoch 131/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5857 - val_accuracy: 0.2500 - val_loss: 0.7029
Epoch 132/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5851 - val_accuracy: 0.2500 - val_loss: 0.7024
Epoch 133/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5847 - val_accuracy: 0.2500 - val_loss: 0.7020
Epoch 134/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5842 - val_accuracy: 0.2500 - val_loss: 0.7015
Epoch 135/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5844 - val_accuracy: 0.2500 - val_loss: 0.7009
Epoch 136/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5835 - val_accuracy: 0.2500 - val_loss: 0.7005
Epoch 137/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5829 - val_accuracy: 0.2500 - val_loss: 0.7000
Epoch 138/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5824 - val_accuracy: 0.2500 - val_loss: 0.6995
Epoch 139/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.5821 - val_accuracy: 0.2500 - val_loss: 0.6990
Epoch 140/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5815 - val_accuracy: 0.2500 - val_loss: 0.6985
Epoch 141/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5815 - val_accuracy: 0.2500 - val_loss: 0.6980
Epoch 142/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.5810 - val_accuracy: 0.2500 - val_loss: 0.6974
Epoch 143/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5801 - val_accuracy: 0.2500 - val_loss: 0.6969
Epoch 144/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5809 - val_accuracy: 0.2500 - val_loss: 0.6964
Epoch 145/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.5792 - val_accuracy: 0.2500 - val_loss: 0.6959
Epoch 146/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.5786 - val_accuracy: 0.2500 - val_loss: 0.6954
Epoch 147/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5788 - val_accuracy: 0.2500 - val_loss: 0.6949
Epoch 148/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5782 - val_accuracy: 0.2500 - val_loss: 0.6944
Epoch 149/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5775 - val_accuracy: 0.2500 - val_loss: 0.6939
Epoch 150/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.5771 - val_accuracy: 0.2500 - val_loss: 0.6934
Epoch 151/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5763 - val_accuracy: 0.2500 - val_loss: 0.6929
Epoch 152/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5758 - val_accuracy: 0.2500 - val_loss: 0.6923
Epoch 153/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5766 - val_accuracy: 0.2500 - val_loss: 0.6918
Epoch 154/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5749 - val_accuracy: 0.2500 - val_loss: 0.6913
Epoch 155/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5753 - val_accuracy: 0.2500 - val_loss: 0.6908
Epoch 156/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5745 - val_accuracy: 0.2500 - val_loss: 0.6903
Epoch 157/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5741 - val_accuracy: 0.2500 - val_loss: 0.6898
Epoch 158/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5739 - val_accuracy: 0.2500 - val_loss: 0.6893
Epoch 159/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5726 - val_accuracy: 0.2500 - val_loss: 0.6888
Epoch 160/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5730 - val_accuracy: 0.2500 - val_loss: 0.6882
Epoch 161/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5715 - val_accuracy: 0.2500 - val_loss: 0.6877
Epoch 162/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5720 - val_accuracy: 0.2500 - val_loss: 0.6872
Epoch 163/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5707 - val_accuracy: 0.2500 - val_loss: 0.6867
Epoch 164/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5710 - val_accuracy: 0.2500 - val_loss: 0.6862
Epoch 165/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5705 - val_accuracy: 0.2500 - val_loss: 0.6856
Epoch 166/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5691 - val_accuracy: 0.2500 - val_loss: 0.6850
Epoch 167/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5694 - val_accuracy: 0.2500 - val_loss: 0.6844
Epoch 168/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5692 - val_accuracy: 0.2500 - val_loss: 0.6838
Epoch 169/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5689 - val_accuracy: 0.2500 - val_loss: 0.6834
Epoch 170/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5675 - val_accuracy: 0.2500 - val_loss: 0.6828
Epoch 171/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5664 - val_accuracy: 0.2500 - val_loss: 0.6822
Epoch 172/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5660 - val_accuracy: 0.2500 - val_loss: 0.6817
Epoch 173/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5655 - val_accuracy: 0.2500 - val_loss: 0.6811
Epoch 174/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5655 - val_accuracy: 0.2500 - val_loss: 0.6806
Epoch 175/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5645 - val_accuracy: 0.2500 - val_loss: 0.6801
Epoch 176/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5639 - val_accuracy: 0.2500 - val_loss: 0.6795
Epoch 177/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5637 - val_accuracy: 0.2500 - val_loss: 0.6790
Epoch 178/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5628 - val_accuracy: 0.2500 - val_loss: 0.6784
Epoch 179/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5637 - val_accuracy: 0.2500 - val_loss: 0.6778
Epoch 180/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5619 - val_accuracy: 0.2500 - val_loss: 0.6772
Epoch 181/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5621 - val_accuracy: 0.2500 - val_loss: 0.6767
Epoch 182/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5616 - val_accuracy: 0.2500 - val_loss: 0.6762
Epoch 183/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5603 - val_accuracy: 0.2500 - val_loss: 0.6756
Epoch 184/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5604 - val_accuracy: 0.2500 - val_loss: 0.6751
Epoch 185/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5593 - val_accuracy: 0.2500 - val_loss: 0.6745
Epoch 186/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5592 - val_accuracy: 0.2500 - val_loss: 0.6739
Epoch 187/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5593 - val_accuracy: 0.2500 - val_loss: 0.6734
Epoch 188/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5577 - val_accuracy: 0.2500 - val_loss: 0.6728
Epoch 189/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5576 - val_accuracy: 0.2500 - val_loss: 0.6723
Epoch 190/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5567 - val_accuracy: 0.2500 - val_loss: 0.6717
Epoch 191/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5561 - val_accuracy: 0.2500 - val_loss: 0.6711
Epoch 192/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5563 - val_accuracy: 0.2500 - val_loss: 0.6705
Epoch 193/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5558 - val_accuracy: 0.2500 - val_loss: 0.6699
Epoch 194/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5546 - val_accuracy: 0.2500 - val_loss: 0.6694
Epoch 195/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5553 - val_accuracy: 0.2500 - val_loss: 0.6688
Epoch 196/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5534 - val_accuracy: 0.2500 - val_loss: 0.6682
Epoch 197/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5530 - val_accuracy: 0.2500 - val_loss: 0.6676
Epoch 198/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5533 - val_accuracy: 0.5000 - val_loss: 0.6671
Epoch 199/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5524 - val_accuracy: 0.5000 - val_loss: 0.6665
Epoch 200/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5515 - val_accuracy: 0.5000 - val_loss: 0.6659
Epoch 201/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5509 - val_accuracy: 0.5000 - val_loss: 0.6654
Epoch 202/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5502 - val_accuracy: 0.5000 - val_loss: 0.6648
Epoch 203/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5508 - val_accuracy: 0.5000 - val_loss: 0.6642
Epoch 204/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5493 - val_accuracy: 0.7500 - val_loss: 0.6635
Epoch 205/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5490 - val_accuracy: 0.7500 - val_loss: 0.6629
Epoch 206/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5482 - val_accuracy: 0.7500 - val_loss: 0.6623
Epoch 207/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5479 - val_accuracy: 0.7500 - val_loss: 0.6617
Epoch 208/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5470 - val_accuracy: 0.7500 - val_loss: 0.6611
Epoch 209/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5464 - val_accuracy: 0.7500 - val_loss: 0.6605
Epoch 210/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5460 - val_accuracy: 0.7500 - val_loss: 0.6599
Epoch 211/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5455 - val_accuracy: 0.7500 - val_loss: 0.6594
Epoch 212/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.5462 - val_accuracy: 0.7500 - val_loss: 0.6588
Epoch 213/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.5446 - val_accuracy: 0.7500 - val_loss: 0.6582
Epoch 214/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7500 - loss: 0.5438 - val_accuracy: 0.7500 - val_loss: 0.6576
Epoch 215/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5432 - val_accuracy: 0.7500 - val_loss: 0.6570
Epoch 216/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5426 - val_accuracy: 0.7500 - val_loss: 0.6564
Epoch 217/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.5422 - val_accuracy: 0.7500 - val_loss: 0.6558
Epoch 218/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5415 - val_accuracy: 0.7500 - val_loss: 0.6552
Epoch 219/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5409 - val_accuracy: 0.7500 - val_loss: 0.6545
Epoch 220/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5403 - val_accuracy: 0.7500 - val_loss: 0.6539
Epoch 221/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5417 - val_accuracy: 0.7500 - val_loss: 0.6532
Epoch 222/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.5393 - val_accuracy: 0.7500 - val_loss: 0.6526
Epoch 223/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5387 - val_accuracy: 0.7500 - val_loss: 0.6520
Epoch 224/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.5395 - val_accuracy: 0.7500 - val_loss: 0.6514
Epoch 225/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5383 - val_accuracy: 0.7500 - val_loss: 0.6508
Epoch 226/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8333 - loss: 0.5370 - val_accuracy: 0.7500 - val_loss: 0.6502
Epoch 227/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.5371 - val_accuracy: 0.7500 - val_loss: 0.6496
Epoch 228/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5383 - val_accuracy: 0.7500 - val_loss: 0.6489
Epoch 229/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8333 - loss: 0.5359 - val_accuracy: 0.7500 - val_loss: 0.6482
Epoch 230/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5356 - val_accuracy: 0.7500 - val_loss: 0.6476
Epoch 231/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5348 - val_accuracy: 0.7500 - val_loss: 0.6469
Epoch 232/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5335 - val_accuracy: 0.7500 - val_loss: 0.6463
Epoch 233/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5330 - val_accuracy: 0.7500 - val_loss: 0.6457
Epoch 234/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8333 - loss: 0.5331 - val_accuracy: 0.7500 - val_loss: 0.6451
Epoch 235/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5318 - val_accuracy: 0.7500 - val_loss: 0.6444
Epoch 236/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8333 - loss: 0.5312 - val_accuracy: 0.7500 - val_loss: 0.6438
Epoch 237/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8333 - loss: 0.5318 - val_accuracy: 0.7500 - val_loss: 0.6432
Epoch 238/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5311 - val_accuracy: 0.7500 - val_loss: 0.6425
Epoch 239/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5309 - val_accuracy: 0.7500 - val_loss: 0.6418
Epoch 240/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5288 - val_accuracy: 0.7500 - val_loss: 0.6411
Epoch 241/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8333 - loss: 0.5284 - val_accuracy: 0.7500 - val_loss: 0.6404
Epoch 242/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5305 - val_accuracy: 0.7500 - val_loss: 0.6396
Epoch 243/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5274 - val_accuracy: 0.7500 - val_loss: 0.6390
Epoch 244/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.5273 - val_accuracy: 0.7500 - val_loss: 0.6382
Epoch 245/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5258 - val_accuracy: 0.7500 - val_loss: 0.6375
Epoch 246/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5252 - val_accuracy: 0.7500 - val_loss: 0.6368
Epoch 247/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8333 - loss: 0.5254 - val_accuracy: 0.7500 - val_loss: 0.6361
Epoch 248/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5241 - val_accuracy: 0.7500 - val_loss: 0.6354